apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react
  name: react
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - image: yoniss/react-expense:18
          name: expense-spring
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: react
  name: react
spec:
  ports:
    - name: "http"
      port: 3000
      targetPort: 3000
  selector:
    app: react
  type: LoadBalancer

